# Generated by Django 5.2.10 on 2026-03-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('loc', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('mba', 'mba'), ('mca', 'mca'), ('btech', 'btech')], max_length=50)),
            ],
        ),
    ]
